version: '2'

networks:
  alice-net:

services:
  alice:
    container_name: luigi
    hostname: alice
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8082:8082"  
    environment:
      LUIGI_TASK_HISTORY_DB_CONNECTION: postgresql://luigi@db/dev
      LUIGI_SCHEDULER_RECORD_TASK_HISTORY: true
      INPUT_DIR: '/input' 
      OUTPUT_DIR: '/output'      
    depends_on:
      - db
    entrypoint:
      - ./wait-for-postgres.sh
      - db   
    networks:
      alice-net:  
    volumes:
      - ${INPUT_DIR}:/input
      - ${OUTPUT_DIR}:/output          

  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: luigi
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dev
    networks:
      alice-net: