version: '2'

networks:
  alice-net:

services:
  scheduler:
    container_name: alice.luigi2
    build:
      context: docker/luigi
    ports:
      - "8082:8082"
    volumes:
      - .:/alice      
    environment:
      LUIGI_TASK_HISTORY_DB_CONNECTION: postgres://luigi@db/dev
      LUIGI_SCHEDULER_RECORD_TASK_HISTORY: "true"
    depends_on:
      - db
    entrypoint:
      - ./wait-for-postgres.sh
      - db   
    networks:
      alice-net:      

  # worker:    
  #   build:
  #     dockerfile: docker/worker/Dockerfile
  #     context: .
  #   # hostname: worker
  #   volumes:
  #     - .:/alice
  #   environment:
  #     LUIGI_CORE_DEFAULT-SCHEDULER-URL: http://scheduler:8082
  #   depends_on:
  #     - scheduler
  #   networks:
  #     alice-net:

  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: luigi
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dev
    networks:
      alice-net: